language: java
jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: "dantealighieri1265"
    token: 9dd9952a768e6a3d174539e86cbe89c644256fc3

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean
  - mvn clean verify sonar:sonar